name: Bug reporting
description: Reporting new bugs
title: 'BUG -'
labels: bug
projects: IMAP
body:
- type: textarea
  attributes:
    label: "## Description of the issue"
- type: textarea
  attributes:
    label: "### Steps to reproduce the issue

    1.
    2.
    3."
- type: textarea
  attributes:
    label: "### Code Snippet:"
    value: "# Code"
    render: python
- type: textarea
  attributes:
    label: "### Expected behavior (What should happen)"
- type: textarea
  attributes:
    label: "### Actual behavior (What does happen)"
- type: textarea
  attributes:
    label: "#### Additional notes"
- type: textarea
  attributes:
    label: "### Affected areas (code, data, or process)"
- type: textarea
  attributes:
    label: "### Suggested fix?"