name: Documentation Issue
description: Creating or updating documentation 
labels: documentation
projects: IMAP
body:
- type: textarea
  attributes:
    label: "Overview"
- type: textarea
  attributes:
    label: "Related documents or information sources"
