name: Reprocess Request
description: Template for product reprocessing requests
title: "[REPROCESS] "
labels:
  - reprocess
body:
  - type: markdown
    attributes:
      value: Please provide all required information for this product reprocessing request.

  - type: input
    attributes:
      label: Instrument
      description: Which instrument? It can be one or more instruments.
      placeholder: "e.g., MAG, GLOWS"
    validations:
      required: true

  - type: input
    attributes:
      label: Start Date of the data to reprocess
      description: Start date of the date range for data to reprocess (format YYYYMMDD)
      placeholder: "YYYYMMDD (e.g., 20260101)"
    validations:
      required: true

  - type: input
    attributes:
      label: End Date of the data to reprocess
      description: End date of the date range for data to reprocess (format YYYYMMDD)
      placeholder: "YYYYMMDD (e.g., 20260531)"
    validations:
      required: true

  - type: input
    attributes:
      label: Data Level
      description: What product or data level needs to be reprocessed?
      placeholder: "e.g., L1A, L2, L3"

  - type: input
    attributes:
      label: Descriptor
      description: Data descriptor for the reprocessing (optional)
      placeholder: "e.g., reprocessing only certain descriptor"

  - type: textarea
    attributes:
      label: Additional Information
      description: Add any other relevant details or special requirements here